spring:
  application:
    name: email-service

server:
  port: 8081

data:
  cassandra:
    keyspace-name: testKeySpace
    contact-points: 127.0.0.1
    port: 9142
    local-datacenter: datacenter1

mail:
  host: smtp.gmail.com
  port: 587
  username: eduardodasilvadandolini@gmail.com
  password: 06122004Ae$edu
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true

kafka:
  consumer:
    bootstrap-servers: localhost:9092
    group-id: notificationConfirmation
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: '*'
      spring.json.type.mapping: notificationConfirmation:com.challenge.magalu.kafka.NotificationConfirmation
