spring:
  application:
    name: email-service

  mongodb:
    username: mongo
    password: mongo
    host: localhost
    port: 27017
    database: email
    authentication-database: admin

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notificationConfirmation
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: notificationConfirmation:com.ms.email_service.kafka.NotificationConfirmation
      listener:
        missing-topics-fatal: false

server:
  port: 8082
